/*
// This software is subject to the terms of the Eclipse Public License v1.0
// Agreement, available at the following URL:
// http://www.eclipse.org/legal/epl-v10.html.
// You must accept the terms of that agreement to use this software.
//
// Copyright (C) 2026 Spicule / Saiku community
// All Rights Reserved.
*/
package mondrian.property;

import static dev.hegel.Generators.binary;
import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import dev.hegel.HegelTest;
import dev.hegel.TestCase;
import java.util.Arrays;
import mondrian.util.Base64;
import mondrian.util.ByteString;

/**
 * Properties of Mondrian's binary codecs.
 *
 * <p>{@link ByteString} is the identity of a cached schema — {@code RolapSchema} keys its schema
 * pool by the MD5 of the schema content, so {@code equals}, {@code hashCode} and {@code compareTo}
 * decide whether two schemas are considered the same. A bug there does not corrupt a byte; it hands
 * one tenant another tenant's cached schema.
 *
 * <p>These are contract properties: the {@code equals}/{@code hashCode}/{@code compareTo} laws the
 * JDK collections assume but never check. Generated bytes cover the boundaries that hand-written
 * tests skip — empty arrays, and the sign boundary at {@code 0x80} where a {@code byte} compared as
 * a signed value orders differently from the same byte compared as unsigned.
 */
class BinaryCodecPropertyTest {

    // ------------------------------------------------------------------
    // Base64
    // ------------------------------------------------------------------

    /** Decoding an encoding returns the original bytes. */
    @HegelTest(testCases = 300)
    void base64RoundTrips(TestCase tc) {
        byte[] bytes = tc.draw(binary().maxSize(64), "bytes");

        String encoded = Base64.encodeBytes(bytes);
        byte[] decoded = Base64.decode(encoded);

        assertArrayEquals(bytes, decoded, () -> "round trip changed the bytes via " + encoded);
    }

    /** Encoding agrees with the JDK's Base64 implementation. */
    @HegelTest(testCases = 300)
    void base64AgreesWithTheJdk(TestCase tc) {
        byte[] bytes = tc.draw(binary().maxSize(64), "bytes");

        // Mondrian's encoder inserts line breaks past a threshold; the JDK MIME encoder is the
        // matching variant, but comparing decoded forms avoids depending on the exact wrapping
        // and still pins the encoding itself.
        byte[] viaJdk = java.util.Base64.getMimeDecoder().decode(Base64.encodeBytes(bytes));

        assertArrayEquals(bytes, viaJdk, "the JDK could not decode what Mondrian encoded");
    }

    // ------------------------------------------------------------------
    // ByteString contracts
    // ------------------------------------------------------------------

    /** Equal contents imply equal objects and equal hash codes. */
    @HegelTest(testCases = 300)
    void byteStringEqualityFollowsContents(TestCase tc) {
        byte[] bytes = tc.draw(binary().maxSize(32), "bytes");

        ByteString a = new ByteString(bytes);
        ByteString b = new ByteString(bytes.clone());

        assertEquals(a, b, "equal contents must be equal");
        assertEquals(a.hashCode(), b.hashCode(), "equal objects must have equal hash codes");
        assertEquals(0, a.compareTo(b), "equal objects must compare equal");
    }

    /**
     * {@code compareTo} is antisymmetric and consistent with {@code equals}.
     *
     * <p>{@code ByteString} is {@link Comparable} and ends up in sorted collections, where a
     * comparator that disagrees with {@code equals} produces lookups that miss elements the set
     * demonstrably contains.
     */
    @HegelTest(testCases = 400)
    void byteStringComparisonIsATotalOrder(TestCase tc) {
        ByteString a = new ByteString(tc.draw(binary().maxSize(8), "a"));
        ByteString b = new ByteString(tc.draw(binary().maxSize(8), "b"));

        int ab = a.compareTo(b);
        int ba = b.compareTo(a);

        assertEquals(Integer.signum(ab), -Integer.signum(ba), () -> "antisymmetry broken for " + a + " and " + b);
        assertEquals(
                ab == 0,
                a.equals(b),
                () -> "compareTo and equals disagree for " + a + " and " + b);
    }

    /** {@code compareTo} is transitive. */
    @HegelTest(testCases = 400)
    void byteStringComparisonIsTransitive(TestCase tc) {
        ByteString a = new ByteString(tc.draw(binary().maxSize(6), "a"));
        ByteString b = new ByteString(tc.draw(binary().maxSize(6), "b"));
        ByteString c = new ByteString(tc.draw(binary().maxSize(6), "c"));

        if (a.compareTo(b) <= 0 && b.compareTo(c) <= 0) {
            assertTrue(a.compareTo(c) <= 0, () -> "transitivity broken: " + a + " <= " + b + " <= " + c);
        }
    }

    /** {@code length} and {@code byteAt} expose exactly the bytes handed in. */
    @HegelTest(testCases = 300)
    void byteStringExposesItsBytes(TestCase tc) {
        byte[] bytes = tc.draw(binary().maxSize(32), "bytes");
        ByteString subject = new ByteString(bytes);

        assertEquals(bytes.length, subject.length(), "length");
        for (int i = 0; i < bytes.length; i++) {
            assertEquals(bytes[i], subject.byteAt(i), "byte at " + i + " of " + Arrays.toString(bytes));
        }
    }
}
